<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Classic Cotton T-Shirt',
                'description' => '100% cotton comfortable t-shirt for everyday wear. Available in multiple colors and sizes.',
                'price' => 25.99,
                'sale_price' => 19.99,
                'stock_quantity' => 100,
                'sku' => 'MTS-001',
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Denim Jeans - Slim Fit',
                'description' => 'Premium denim jeans with slim fit design. Perfect for casual and semi-formal occasions.',
                'price' => 59.99,
                'sale_price' => 49.99,
                'stock_quantity' => 75,
                'sku' => 'MJE-002',
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Formal Dress Shirt',
                'description' => 'Elegant formal shirt made from high-quality cotton. Ideal for office wear and formal events.',
                'price' => 45.99,
                'sale_price' => null,
                'stock_quantity' => 60,
                'sku' => 'MFS-003',
                'image' => 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sports Jacket',
                'description' => 'Lightweight sports jacket with water-resistant coating. Great for outdoor activities.',
                'price' => 89.99,
                'sale_price' => 79.99,
                'stock_quantity' => 40,
                'sku' => 'MSJ-004',
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casual Shorts',
                'description' => 'Comfortable cotton shorts for summer wear. Available in various colors and patterns.',
                'price' => 35.99,
                'sale_price' => 29.99,
                'stock_quantity' => 85,
                'sku' => 'MCS-005',
                'image' => 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Winter Sweater',
                'description' => 'Warm wool blend sweater for cold weather. Stylish and comfortable design.',
                'price' => 65.99,
                'sale_price' => 55.99,
                'stock_quantity' => 50,
                'sku' => 'MWS-006',
                'image' => 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leather Belt',
                'description' => 'Genuine leather belt with classic buckle design. Durable and stylish accessory.',
                'price' => 29.99,
                'sale_price' => 24.99,
                'stock_quantity' => 120,
                'sku' => 'MBL-007',
                'image' => 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Running Shoes',
                'description' => 'Lightweight running shoes with cushion technology. Perfect for sports and daily use.',
                'price' => 79.99,
                'sale_price' => 69.99,
                'stock_quantity' => 65,
                'sku' => 'MSH-008',
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Business Suit - 2 Piece',
                'description' => 'Elegant business suit with jacket and trousers. Perfect for formal occasions and office wear.',
                'price' => 199.99,
                'sale_price' => 179.99,
                'stock_quantity' => 30,
                'sku' => 'MBS-009',
                'image' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casual Hoodie',
                'description' => 'Comfortable cotton hoodie with front pocket. Great for casual outings and lounging.',
                'price' => 49.99,
                'sale_price' => 39.99,
                'stock_quantity' => 90,
                'sku' => 'MCH-010',
                'image' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Swim Trunks',
                'description' => 'Quick-dry swim trunks with stylish patterns. Perfect for beach and pool activities.',
                'price' => 34.99,
                'sale_price' => 27.99,
                'stock_quantity' => 70,
                'sku' => 'MST-011',
                'image' => 'https://images.unsplash.com/photo-1529903384028-929ae5dccdf1?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leather Wallet',
                'description' => 'Genuine leather wallet with multiple card slots and cash compartment. Durable and stylish.',
                'price' => 42.99,
                'sale_price' => 35.99,
                'stock_quantity' => 110,
                'sku' => 'MWL-012',
                'image' => 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baseball Cap',
                'description' => 'Classic baseball cap with adjustable strap. Available in various team colors and designs.',
                'price' => 22.99,
                'sale_price' => 18.99,
                'stock_quantity' => 150,
                'sku' => 'MBC-013',
                'image' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dress Shoes - Oxford',
                'description' => 'Elegant oxford dress shoes made from genuine leather. Perfect for formal occasions.',
                'price' => 129.99,
                'sale_price' => 109.99,
                'stock_quantity' => 45,
                'sku' => 'MDS-014',
                'image' => 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Winter Coat',
                'description' => 'Heavy winter coat with insulation and water-resistant exterior. Perfect for cold climates.',
                'price' => 149.99,
                'sale_price' => 129.99,
                'stock_quantity' => 35,
                'sku' => 'MWC-015',
                'image' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Athletic Socks - 6 Pack',
                'description' => 'Comfortable athletic socks with cushion support. Pack of 6 pairs in various colors.',
                'price' => 24.99,
                'sale_price' => 19.99,
                'stock_quantity' => 200,
                'sku' => 'MAS-016',
                'image' => 'https://images.unsplash.com/photo-1587271636243-d4c3170a7c9d?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Polo Shirt',
                'description' => 'Classic polo shirt made from breathable cotton blend. Perfect for casual and smart casual wear.',
                'price' => 39.99,
                'sale_price' => 32.99,
                'stock_quantity' => 80,
                'sku' => 'MPS-017',
                'image' => 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600&h=400&fit=crop',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}